#!/bin/bash
set -exu -o pipefail

function test_latest() {
  tag=latest
  echo "Testing ${tag} Dockerfile"

  docker run -it "trussworks/nuker:${tag}" aws version
  docker run -it "trussworks/nuker:${tag}" aws-nuke --version

  echo "Passed ${tag}"
}

tag=latest
echo "* Testing USER is properly set to 'circleci' on '${tag}' tagged image"
docker run -it trussworks/nuker:$tag bash -xc '[[ $(whoami) = circleci ]]'
test_latest

echo Passed.
exit 0